apiVersion: v1
kind: Namespace
metadata:
  name: lab-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: lab-prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: lab-apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: lab-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              memory: 64Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
  namespace: lab-dev
type: Opaque
stringData:
  mensaje: "Ana no debe poder leer este valor"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: lab-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              memory: 64Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
  namespace: lab-prod
type: Opaque
stringData:
  mensaje: "Producción contiene datos más sensibles"
